AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudwatch Cleaner StackSet
Parameters:
  EnvName:
    Type: String
    Description: (Optional) Name of the account.
    AllowedPattern: ^.*[^0-9]$
  LambdaS3Key:
    Description: S3 warfile key path to lambda function.
    Type: String
Outputs:
  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value:
      Fn::GetAtt:
        - iamRole
        - "Arn"
    Export:
      Name:
        Fn::Sub: iamRole
  LambdaFunctionName:
    Value:
      Ref: CloudwatchCleanerFunction
  LambdaFunctionARN:
    Description: Lambda Function ARN.
    Value:
      Fn::GetAtt:
        - CloudwatchCleanerFunction
        - "Arn"
    Export:
      Name:
        Fn::Sub: LambdaARN-${EnvName}
Resources:
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: cloudwatch-alarms
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - cloudwatch:DescribeAlarms
                - cloudwatch:DeleteAlarms
                Effect: Allow
                Resource: '*'
        - PolicyName: ec2-instances
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - ec2:DescribeInstances
                - ec2:DescribeTags
                Effect: Allow
                Resource: '*'
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - logs:createLogGroup
                - logs:createLogStream
                Effect: Allow
                Resource: '*'
      RoleName: iam-cloudwatch-cleaner-role
  CloudwatchCleanerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: cloudwatch-cleaner-function-${EnvName}
      Description: Cloudwatch Cleaner Lambda Job
      Environment:
        Variables:
          loglevel: INFO
      Runtime: python3.7
      Code:
        S3Bucket: core-tech-ops
        S3Key:
          Ref: LambdaS3Key
      Handler: Cloudwatch_Clearner_Test.lambda_handler
      MemorySize: 128
      Timeout: 900
      Role: !GetAtt iamRole.Arn
  CloudwatchCleanerPolicy:        
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CloudwatchCleanerFunction
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        !GetAtt
          - CloudwatchCleanerSchedule
          - Arn
  CloudwatchCleanerSchedule:
    Type: AWS::Events::Rule
    Properties:
      Description: Scheduler for Cloudwatch Cleaner Script
      Name: CloudwatchCleanerSchedule
      ScheduleExpression: cron(0 8 1 * ? *)
      State: ENABLED
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - CloudwatchCleanerFunction
              - "Arn"
          Id: CloudwatchCleanerFunction